name: tires
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  http: ^1.2.1
  shared_preferences: ^2.0.8
  image_picker: ^0.8.6
  path_provider: ^2.0.5
  path: ^1.9.0
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.1
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  smooth_page_indicator: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/foreground_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dotted_border: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/icon.png
    - images/logo.png
    - images/logo@2x.png
    - images/Icon@2x.png
    - images/english_flag.png
    - images/english_flag@2x.png
    - images/arabic_flag.png
    - images/arabic_flag@2x.png
    - images/walkthrough/bg1.jpeg
    - images/walkthrough/bg2.jpeg
    - images/walkthrough/bg3.jpeg
    - images/walkthrough/bg4.jpeg
    - images/walkthrough/bg5.jpeg
    - images/walkthrough/bg6.jpeg
    - images/walkthrough/bg7.jpeg
    - images/home/Alert.png
    - images/home/Alert@2x.png
    - images/home/alertdot.png
    - images/home/alertdot@2x.png
    - images/home/cart@2x.png
    - images/home/cart.png
    - images/home/menu.png
    - images/home/menu@2x.png
    - images/home/f1.png
    - images/home/f2.png
    - images/home/l1.png
    - images/home/l2.png
    - images/fourXfour/bg1.png
    - images/fourXfour/1.png
    - images/fourXfour/2.png
    - images/fourXfour/3.png
    - images/fourXfour/4.png
    - images/fourXfour/5.png
    - images/fourXfour/6.png
    - images/tiresandwheels/bg1.png
    - images/tiresandwheels/1.png
    - images/tiresandwheels/2.png
    - images/tiresandwheels/3.png
    - images/tiresandwheels/4.png
    - images/featuredproducts/bg1.png
    - images/featuredproducts/1.png
    - images/featuredproducts/2.png
    - images/featuredproducts/3.png
    - images/featuredproducts/4.png
    - images/payment/visa.png
    - images/payment/master.png
    - images/payment/american.png
    - images/payment/discover.png
    - images/payment/success.png
    - images/notification/bag.png
    - images/notification/tag.png



  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
          
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  